### ISSUE TITLE
Some images are not contained in the dataset (bamboo_images).

### ISSUE THREAD

**Issue by cxxgtxy** [OpenLAMM/LAMM#13]
Hi,
Please check the following images are not included (broken) in the bamboo_images. I don't iter the whole dataset.
bamboo_images/0da6411bc9c3cf1973fab4a143866cd5cc1d7bd2.tablet_computer_home.jpeg
bamboo_images/faa5594fbc9d7ee0d125e58a3cb911092d6be990.lighthouse_person.jpeg

Thanks!

**Comment by double125** [comment]
> 您好， 请检查以下图像是否包含在（损坏的）bamboo_images 中。我不会迭代整个数据集。 竹子图像/0da6411bc9c3cf1973fab4a143866cd5cc1d7bd2.tablet_computer_home.jpeg 竹子图像/faa5594fbc9d7ee0d125e58a3cb911092d6be990.lighthouse_person.jpeg
> 
> 谢谢！

We have discovered this issue, the information of these two images is broken, we will deal with it as soon as possible and update the bamboo image set.
In addition, if you are in a hurry to train our code and model, you can skip these two images directly, which will have little impact on the final model performance.

**Comment by cxxgtxy** [comment]
Thanks
