### ISSUE TITLE
Evaluation code is not complete.

### ISSUE THREAD

**Issue by cxxgtxy** [OpenLAMM/LAMM#14]
NameError: name 'collate_fn' is not defined
<img width="683" alt="image" src="https://github.com/OpenLAMM/LAMM/assets/9956912/f6c9b72f-e772-426c-a107-7ea6de414bc3">

**Comment by wangjiongw** [comment]
Thanks for your issue and sorry for the mistake. We have add the missing collate_fn for 2DEvalDataset. Please check it out.
Please let me know if any further questions.

**Comment by cxxgtxy** [comment]
Thanks
