### ISSUE TITLE
How to evaluate on LLaVA and MiniGPT-4？

### ISSUE THREAD

**Issue by waltonfuture** [OpenLAMM/LAMM#19]
Can you release the codes about how to send the datasets into LLaVA and MiniGPT-4 for eval? There are only codes about how to evaluate the context generated by LLaVA and MiniGPT-4.

**Comment by Coach257** [comment]
Thanks for the issue. We have not yet integrated other models into our code framework, so for now please use the official code to generate answers and then run our common_eval_2d.py script. [LLaVA](https://github.com/haotian-liu/LLaVA/blob/main/llava/eval/run_llava.py) and [MiniGPT-4](https://github.com/Vision-CAIR/MiniGPT-4/blob/main/demo.py) provide demo code that allows you to easily obtain model answers by inputting the "image" and "query". We provide the `data['image']` and `data['query']` in the test data JSON file. Additionally, it's important to use the same system message in [[src/datasets/system_msg.py](https://github.com/OpenLAMM/LAMM/blob/main/src/datasets/system_msg.py)](url) to ensure a fair comparison.
