### ISSUE TITLE
Seemly not freeze llama

### ISSUE THREAD

**Issue by jinyutong23** [OpenLAMM/LAMM#23]
When I train LAMM on NTX 3090 24G with 1 batch size be setted, the GPU memory fill up.
I check out my hyper-parameter, it still not solve the abnormal.      So I look your code and not found the operation about freeze model excluding freeze visual encoder.
I don't know the reason that the strange phenomenon GPU memory brake out.   Should I add a freeze module in precent code?
![Snipaste_2023-07-03_13-51-19](https://github.com/OpenLAMM/LAMM/assets/109946035/8f77f4cc-25b1-4998-bd1a-81abae621ce3)

**Comment by wangjiongw** [comment]
Hi, thanks for your interest in our work. May I know the size of vicuna model you used?

**Comment by wangjiongw** [comment]
> When I train LAMM on NTX 3090 24G with 1 batch size be setted, the GPU memory fill up. I check out my hyper-parameter, it still not solve the abnormal. So I look your code and not found the operation about freeze model excluding freeze visual encoder. I don't know the reason that the strange phenomenon GPU memory brake out. Should I add a freeze module in precent code? ![Snipaste_2023-07-03_13-51-19](https://user-images.githubusercontent.com/109946035/250468498-8f77f4cc-25b1-4998-bd1a-81abae621ce3.png)

I think explicitly freeze llama_model is not suitable here, as the lora parameters are also included in `self.llama_model.named_parameters`.
Since we use `PEFT` package to add LoRA to LLM, I think the non-LoRA parameters has been freezed by the function [mark_only_lora_as_trainable](https://github.com/huggingface/peft/blob/032fff92fb74b737a2934e91a08d82142fb79dc3/src/peft/tuners/lora.py#L500). Please check it out.

If you're using the 13B vicuna model, maybe you can try to use the 7B one.

**Comment by jinyutong23** [comment]
@wangjiongw  We set vicuna-7B for llama pretrain.    And something strange that although i add freeze operation as mentioned above, the GPU memory still fill up.
![image](https://github.com/OpenLAMM/LAMM/assets/109946035/6373109e-65b7-488c-b0d0-234e43e0b5dd)
![image](https://github.com/OpenLAMM/LAMM/assets/109946035/998de2a7-2e73-4d04-be3b-376a8417eb3c)
![image](https://github.com/OpenLAMM/LAMM/assets/109946035/1567e276-ba78-4999-b042-6c821b3126d0)

**Comment by jinyutong23** [comment]
> > When I train LAMM on NTX 3090 24G with 1 batch size be setted, the GPU memory fill up. I check out my hyper-parameter, it still not solve the abnormal. So I look your code and not found the operation about freeze model excluding freeze visual encoder. I don't know the reason that the strange phenomenon GPU memory brake out. Should I add a freeze module in precent code? ![Snipaste_2023-07-03_13-51-19](https://user-images.githubusercontent.com/109946035/250468498-8f77f4cc-25b1-4998-bd1a-81abae621ce3.png)
> 
> I think explicitly freeze llama_model is not suitable here, as the lora parameters are also included in `self.llama_model.named_parameters`. Since we use `PEFT` package to add LoRA to LLM, I think the non-LoRA parameters has been freezed by the function [mark_only_lora_as_trainable](https://github.com/huggingface/peft/blob/032fff92fb74b737a2934e91a08d82142fb79dc3/src/peft/tuners/lora.py#L500). Please check it out.
> 
> If you're using the 13B vicuna model, maybe you can try to use the 7B one.

Thank your anwser! The llama pretrain not necessary to freeze again. However, I still feel confuse about the GPU memeory broken out under 7B vicuna pretrain.

**Comment by wangjiongw** [comment]
> > > When I train LAMM on NTX 3090 24G with 1 batch size be setted, the GPU memory fill up. I check out my hyper-parameter, it still not solve the abnormal. So I look your code and not found the operation about freeze model excluding freeze visual encoder. I don't know the reason that the strange phenomenon GPU memory brake out. Should I add a freeze module in precent code? ![Snipaste_2023-07-03_13-51-19](https://user-images.githubusercontent.com/109946035/250468498-8f77f4cc-25b1-4998-bd1a-81abae621ce3.png)
> > 
> > 
> > I think explicitly freeze llama_model is not suitable here, as the lora parameters are also included in `self.llama_model.named_parameters`. Since we use `PEFT` package to add LoRA to LLM, I think the non-LoRA parameters has been freezed by the function [mark_only_lora_as_trainable](https://github.com/huggingface/peft/blob/032fff92fb74b737a2934e91a08d82142fb79dc3/src/peft/tuners/lora.py#L500). Please check it out.
> > If you're using the 13B vicuna model, maybe you can try to use the 7B one.
> 
> Thank your anwser! The llama pretrain not necessary to freeze again. However, I still feel confuse about the GPU memeory broken out under 7B vicuna pretrain.

As we trained our model on A100 previously, this is a quite new problem. I tested on our device and found that 7B model requires about 30GB GPU memory. 
We are also trying to optimize GPU memory consumption and enable training on devices such as 3090, please stay tuned. 
Maybe you can try to apply `INT8` to LLM parameters to save memory consumption first. Contributions are also welcomed and appreciated.
