### ISSUE TITLE
Where is the  'cli_demo_pcl.py' file?

### ISSUE THREAD

**Issue by SCLBD** [OpenLAMM/LAMM#25]
I want to run the CLI demo in the README.
`   
    cd ./src
    python cli_demo_pcl.py \
        --model lamm_peft \
        --vision_type pcl/image \
        --encoder_pretrain epcl/clip \
        --encoder_ckpt_path $EPCL_CKPT_PATH \
        --vicuna_ckpt_path $LLM_CKPT_PATH \
        --delta_ckpt_path $LAMM_CKPT_PATH
`
However, I can not find the **cli_demo_pcl.py** file in the _src_ folder.

**Comment by wangjiongw** [comment]
Thanks for your issue. The cli_demo.py was accidently deleted at that commit, sorry for mistakes.
Please check the most recent commit in main branch. Now you can follow the [instruction](https://github.com/OpenLAMM/LAMM#cli-demo) and run [cli_demo.py](https://github.com/OpenLAMM/LAMM/blob/main/src/cli_demo.py) for command line demo, even for 13B LLM models.
