### ISSUE TITLE
论文结果

### ISSUE THREAD

**Issue by qidianliuh** [OpenLAMM/LAMM#26]
@Coach257 你好，我使用官方提供的ViT-L-14、vicuna-13b-v1.3、lamm-13b-lora32-186k作为权重，使用LAMM_2D_Evaluation.sh生成answer，得到的结果中有三个结果和原文差异较大，我得到的结果如下：CIFAR10->0.19%，VOC2012->0.72，SVT->0.77。请问这可能是什么原因造成的呢？

**Comment by wangjiongw** [comment]
Thanks for interest in our work. The Vicuna model we used is Vicuna-13b-v0, maybe you can change to the version and try again. Sorry for misundertanding caused, we'll make it clear in README.
感谢您的提问。我们论文中和公布的checkpoint都是基于Vicuna 13b v0训练的，麻烦切换到对应版本之后进行测试。非常抱歉造成歧义，我们之后会在文档中更新。
