### ISSUE TITLE
Enable batch inference in some datasets

### ISSUE THREAD

**Issue by lighten001** [OpenLAMM/LAMM#27]
now there are some dataset which can only use single inference, such as:
```python
single_infernce_dataset = [
    'FSC147','SQAimage','AI2D'
]
```
maybe it's possible to enable batch for some of them

**Comment by Coach257** [comment]
Thank you for your issue and your interest in our work. We appreciate your feedback and agree that there is room for optimization in our code. However, we would like to let you know that we have identified bugs in the datasets (FSC147, SQAimage, AI2D) you mentioned during batch inference testing. We will work on fixing this issue in the near future.
