### ISSUE TITLE
Ch3Ef dataset is not avaliable

### ISSUE THREAD

**Issue by Aldebaranus** [OpenLAMM/LAMM#76]
Hi, thank you for your great work. The dataset [link](https://huggingface.co/datasets/openlamm/Ch3Ef) for Ch3Ef does not appear to be available.

**Comment by Coach257** [comment]
We are currently preparing for an ICML workshop where chef's data will be used in the challenge, so we have closed the dataset for the time being, and we will open the dataset as soon as everything prepared.

**Comment by MelikaNobakhtian** [comment]
> We are currently preparing for an ICML workshop where chef's data will be used in the challenge, so we have closed the dataset for the time being, and we will open the dataset as soon as everything prepared.

Hi again!
I just want to ask that where will be the release time for dataset? Because ICML is over.

**Comment by wangjiongw** [comment]
> > We are currently preparing for an ICML workshop where chef's data will be used in the challenge, so we have closed the dataset for the time being, and we will open the dataset as soon as everything prepared.
> 
> Hi again! I just want to ask that where will be the release time for dataset? Because ICML is over.

You may find the dataset at this [huggingface link](https://huggingface.co/datasets/openlamm/Ch3Ef/tree/main).
